### ISSUE TITLE
Patterns: Add Data Visualization Guidance Section

### ISSUE THREAD

**Issue by davezen1** [US-CBP/cbp-style-guide#21]
As a developer, I would like a data visualization section with guidance and examples so that I can apply data visualization best practices.
- We need to add a section and talk about guidance not necessarily specific libraries.

**Comment by HMcFabulous** [comment]
(H1) Data Visualization
(H2) Overview
It is sometimes important to communicate detailed information to users visually. This increases content digestion while simultaneously making page content more engaging. The primary goal of this effort is to make information more intellectually distinct, not more decorative. 
When bold shapes and contrasted colors are used with responsive actions, users have increased comprehension.
(H2) Usage
You can bring increased clarity to your information by considering your page layout early on. We advise against having more than 3 graphical elements on one page.  

 
![chart-123](https://cloud.githubusercontent.com/assets/11233429/19397650/b130aec0-9216-11e6-8ad6-73d1baf35774.jpg)

________________________________________
Section Break
________________________________________
(H2) Charts & Graphs
Some of the most popular chart types can be seen in an example below. It is important to limit the amount of colors you use to draw attention to the metric you are illustration of the metric activated by the user. Avoid showing more than four distinct colors in any one chart. Use grey tones to represent inactive or supporting metrics.

{need illustrations for each of the following}

- Bar Chart
- Line Graphs
- Bullet Chart
- Pie Chart 
    Avoid using a pie chart if your information will be sliced in to 10 or more pieces.
- Metric Counts
   Consider using this approach when using often updated numeric counts. Remember to add supporting formula metrics (example: 50% (50/100)) to tell the whole story.
________________________________________
Section Break
________________________________________
(H2) Maps
[insert paragraph on globe vs. map and raster vs. vector]
