### ISSUE TITLE
Guide: Components - Copy Revisions (C1-10)

### ISSUE THREAD

**Issue by HMcFabulous** [US-CBP/cbp-style-guide#27]
[[Accordions](https://us-cbp.github.io/cbp-style-guide/docs/components/accordions.html)]
C1 - Change "Expand/collapse behaviors" to "Expand/Collapse Behaviors"

[[Contextual alerts](https://us-cbp.github.io/cbp-style-guide/docs/components/alerts.html)]
C2 - Change "Contextual alerts" to "Contextual Alerts"
C3 - Under "Description" replace bulleted text with the following:

- Contextual alerts are positioned above the area or form they relate to
- They are often triggered by a user interaction
- They can be closable and can have other action buttons or links
- Alerts with low importance (info or success) can close automatically after 5 seconds (if desired).
- Alerts with high importance (warning or danger) should not close automatically, unless the situation has been resolved in some other way.

C4 - Replace example Alert copy with the following:

- Press the 'A' key to automatically assign a case. × 
- Case assigned to Jerry [Undo] × 
- Case assigned to Jerry ×
- There are more than 10 cases assigned to John ×
- There was a network error assigning case 90/934,382  [Retry] ×
- Please fix the 3 errors

C5 - Change "System notifications" to "System Notifications"
C6 - Under "Description" remove the period from the bullet "They can be closable and can have other action buttons or links."
C7 - Under "Types:" replace the bulleted text with the following:

- **Info** notifications can be used for general messages that aren’t particularly critical.
- **Success** notifications can be used for positive messages that don’t have a context to associate it with.
- **Warning** notifications can be used for messages that likely require attention.
- **Danger** notifications can be used for critical messages that require immediate attention.

C8 - Replace example System Notification copy with the following:

- Message sent to Jerry × 
- Jerry added a comment to one of your cases (90/098,881) 
View comment × 
- Case 90/842,381 is due tomorrow
View case  Snooze × 
- Connection has been lost. Retrying in 30 seconds.
Retry now × 

C9 - Update System Notification code example with (above) grammatical change.
C10 - Double check that the "Toggle notifications" examples of the toast (that appear in the upper right hand corner of the browser) carry the same changes.

**Comment by davezen1** [comment]
@HMcFabulous not sure of the difference for section: C4 - Replace example Alert copy with the following:

**Comment by davezen1** [comment]
Per @HMcFabulous C4 and C8 we will only use periods at the end of sentences
