### ISSUE TITLE
Components: Contextual Alerts

### ISSUE THREAD

**Issue by HMcFabulous** [US-CBP/cbp-style-guide#28]
Fix justification on 4th example alert. This is the red, double line alert.
![alerts](https://cloud.githubusercontent.com/assets/11233429/18927917/e54b3a1e-858b-11e6-998c-e89f1ed43523.jpg)

**Comment by davezen1** [comment]
@HMcFabulous the alerts were missing the icons.  Take a gander and let me know what you think:

![screen shot 2016-10-21 at 5 34 13 pm](https://cloud.githubusercontent.com/assets/1034574/19612458/aca123aa-97b4-11e6-8cee-087d9aed3bbe.png)
