### ISSUE TITLE
Guide: Components - Copy Revisions (C11-23)

### ISSUE THREAD

**Issue by HMcFabulous** [US-CBP/cbp-style-guide#29]
[[**Breadcrumbs**](https://us-cbp.github.io/cbp-style-guide/docs/components/breadcrumbs.html)]

C11 - Under "Description" replace text with the following:
Breadcrumbs display the current path to a particular page relative to the starting point. Breadcrumbs provide a means for users to understand their current context in a hierarchical structure and the ability to navigate up the structure easily.

- Breadcrumbs display the current path as links separated by carets to indicate each level
- The navigation root is the first element on the left, the current location is the last element to the right
- The current location is not clickable
- Clicking on a link takes you to that screen

Depending on the complexity of the navigational hierarchy and the type of page or application, it may make sense for the breadcrumb to represent only part of the hierarchy while sub tabs/trees/navigation represent the remaining hierarchy. 

[[**Buttons**]](https://us-cbp.github.io/cbp-style-guide/docs/components/buttons.html)
C12 - Replace the paragraph under "Buttons" with the following text:
Buttons are used as action triggers. Depending on the use case, buttons contain a label and/or an icon. There are a variety of styles, sizes, and variations that can be used for different situations.

All button labels are sentence case. Labels should be as short as possible while clearly explaining what will happen when the button is clicked.

C13 - Change "Button styles" to "Button Styles"
C14 - Change "Button sizes" to "Button Sizes"
C15 - Change the text under Button Sizes to:

- Large - use the btn-lg class
- Normal - no extra classes necessary
- Small - use the btn-sm class
- Extra small - use the btn-xs class

C16 - Change "Block level buttons" to "Block Level Buttons"
C17 - Change "Button groups" to "Button Groups"
C18 - Change "Toggle buttons" to "Toggle Buttons"
C19 - Change the copy from "Add the active class and the aria-pressed="true" attribute to a button." to "Add the active class and the aria-pressed="true" attribute to a button to visually hold a depressed state."
C20 - Change "Dropdown buttons" to "Dropdown Buttons"
C21 - Change "Split buttons" to "Split Buttons"
C22 - Change "Icon buttons" to "Icon Buttons"
C23 - Change text from "For an icon without chrome, use a btn-hover." to "For an icon without a border, use a btn-hover."

**Comment by davezen1** [comment]
@HMcFabulous  ready for review

**Comment by davezen1** [comment]
Per @HMcFabulous  closing as updates have been made
