### ISSUE TITLE
Build: CBP Theme should not be bundled as part of vendor.css

### ISSUE THREAD

**Issue by r1teshkumar** [US-CBP/cbp-style-guide#78]
It is impossible to tell looking at the Style Guide where the styles are coming from. The CBP Theme is bundled with several other libraries in a vendor.css. Since the style guide is meant for developers, we should make it clear what libraries are being used if a developer inspects a page using developer tools.

<img width="1088" alt="baddeveloperexperience" src="https://user-images.githubusercontent.com/22313231/35600946-8aec3678-05fe-11e8-8c83-5c3c5566aa41.png">

cc @djKianoosh

**Comment by davezen1** [comment]
This will be more straight forward in a future version of the theme/design system.
