### ISSUE TITLE
Modal header cutoff

### ISSUE THREAD

**Issue by jscharett** [US-CBP/cbp-style-guide#80]
The Dialogs > Live section of the style guide opens up a modal, but the header appears to be cut off.  The modal either does not come down far enough or needs to have its z-index corrected to sit above the toolbar.

**Comment by yellowzapp** [comment]
creating ticket to resolve.
<img width="1685" alt="screen shot 2018-06-28 at 11 56 12 am" src="https://user-images.githubusercontent.com/30844514/42045768-5d38782c-7aca-11e8-8cda-bc266ef17da2.png">
